### ISSUE TITLE
Enable "Always suggest updating pull request branches "

### ISSUE THREAD

**Issue by wmdietl** [jspecify/jdk#116]
For PRs that had merge conflicts, like #105, it is easy to pull in `main` and resolve conflicts.
For PRs without conflicts, like #107, there is no easy option to merge in `main`.

Under project settings, could you enable the "Always suggest updating pull request branches" option? That should then always suggest to pull in `main` if necessary.

**Comment by cpovirk** [comment]
Thanks. I checked the box.
